<?php

	//application details
	$apps[$x]['name'] = "Backup Manager";
	$apps[$x]['uuid'] = "b3d4e7f2-8c9a-4d5e-9f6a-1b2c3d4e5f6a";
	$apps[$x]['category'] = "System";
	$apps[$x]['subcategory'] = "";
	$apps[$x]['version'] = "1.0.0";
	$apps[$x]['license'] = "Mozilla Public License 1.1";
	$apps[$x]['url'] = "https://www.fusionpbx.com";
	$apps[$x]['description']['en-us'] = "Comprehensive tenant-based backup and restore system with scheduling and remote transfer capabilities.";
	$apps[$x]['description']['tr-tr'] = "Zamanlama ve uzak transfer yetenekleri ile kapsamlı tenant bazlı yedekleme ve geri yükleme sistemi.";

	//permission details
	$y = 0;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_view";
	$apps[$x]['permissions'][$y]['menu']['uuid'] = "c5e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_add";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_edit";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_delete";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_restore";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_schedule";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "backup_manager_settings";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";

	//schema details
	$y = 0;
	$apps[$x]['db'][$y]['table']['name'] = "v_backup_manager";
	$apps[$x]['db'][$y]['table']['parent'] = "";
	$z = 0;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_manager_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_name";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Backup name/label";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_type";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Backup type: full, database, recordings, voicemail";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_size";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "bigint";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "bigint";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Backup file size in bytes";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_path";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Full path to backup file";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_status";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Status: pending, processing, completed, failed";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_progress";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "int";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Progress percentage (0-100)";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_metadata";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "JSON metadata (extensions count, recordings count, etc.)";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_date";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Backup creation date";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Record insert date";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "User who created the backup";

	//schedule table
	$y++;
	$apps[$x]['db'][$y]['table']['name'] = "v_backup_schedules";
	$apps[$x]['db'][$y]['table']['parent'] = "";
	$z = 0;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_schedule_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "schedule_name";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Schedule name";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "schedule_enabled";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Schedule enabled status";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "schedule_frequency";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Frequency: hourly, daily, weekly, monthly";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "schedule_time";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Time to run (HH:MM format)";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "schedule_day";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "int";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Day of week (0-6) or month (1-31)";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_type";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Backup type to create";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "retention_days";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "int";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Retention period in days";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "remote_transfer";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable remote transfer after backup";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_run";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Last execution timestamp";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "next_run";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Next scheduled execution";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";

	//settings table
	$y++;
	$apps[$x]['db'][$y]['table']['name'] = "v_backup_settings";
	$apps[$x]['db'][$y]['table']['parent'] = "";
	$z = 0;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "backup_setting_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "setting_name";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Setting name";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "setting_value";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Setting value (encrypted for sensitive data)";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "setting_category";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Category: ftp, sftp, s3, rsync, general";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "setting_enabled";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "boolean";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_user";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";

?>
